const listOfAMC = {
    "1" : "360 ONE Asset Management Limited (Formerly known as IIFL Asset Management Limited)",
    "2" : "Aditya Birla Sun Life AMC Limited",
    "3" : "Axis Asset Management Co. Ltd.",
    "4" : "Bajaj Finserv Asset Management Limited",
    "5" : "Bandhan AMC Limited",
    "6" : "Bank of India Investment Managers Private Limited",
    "7" : "Baroda BNP Paribas Asset Management India Private Limited",
    "8" : "Canara Robeco Asset Management Company Limited",
    "9" : "DSP Asset Managers Private Limited",
    "10" : "Edelweiss Asset Management Limited",
    "11" : "Franklin Templeton Asset Management (India) Private Limited",
    "12" : "Groww Asset Management Limited",
    "13" : "HDFC Asset Management Company Limited",
    "14" : "Helios Capital Asset Management (India) Pvt. Ltd",
    "15" : "HSBC Asset Management (India) Private Ltd",
    "16" : "ICICI Prudential Asset Management Company Limited",
    "17" : "IL&FS Infra Asset Management Limited",
    "18" : "Invesco Asset Management (India) Private Limited",
    "19" : "ITI Asset Management Limited",
    "20" : "JM Financial Asset Management Limited",
    "21" : "Kotak Mahindra Asset Management Company Limited",
    "22" : "LIC Mutual Fund Asset Management Limited",
    "23" : "Mahindra Manulife Investment Management Pvt Ltd",
    "24" : "Mirae Asset Investment Managers (India) Pvt. Ltd",
    "25" : "Motilal Oswal Asset Management Company Limited",
    "26" : "Navi AMC Limited",
    "27" : "Nippon Life India Asset Management Limited",
    "28" : "NJ Asset Management Private Limited",
    "29" : "PGIM India Asset Management Private Limite",
    "30" : "PPFAS Asset Management Pvt. Ltd.",
    "31" : "quant Money Managers Limited",
    "32" : "Quantum Asset Management Company Private Limited",
    "33" : "Sahara Asset Management Company Private Limited",
    "34" : "Samco Asset Management Private Limited",
    "35" : "SBI Funds Management Limited",
    "36" : "Shriram Asset Management Co. Ltd",
    "37" : "Sundaram Asset Management Company Ltd",
    "38" : "Tata Asset Management Limited",
    "39" : "Taurus Asset Management Company Limited",
    "40" : "Trust Asset Management Private Limited",
    "41" : "Union Asset Management Company Private Limited",
    "42" : "UTI Asset Mgmt. Co. Ltd",
    "43" : "WhiteOak Capital Asset Management Limited",
    "44" : "Zerodha Asset Management Private Limited",
    "45" : "Old Bridge Asset Management Pvt. Ltd"
}


const listOfCategory = {
  "1" : "Debt Scheme",
  "2" : "Equity Scheme",
  "3" : "Hybrid Scheme",
  "4" : "Other Scheme",
  "5" : "Solution Oriented Scheme"
}

const subCategory = {
  "1": "Medium to Long Duration Fund",
  "2": "Large Cap Fund",
  "3": "Liquid Fund",
  "4": "Gilt Fund",
  "5": "Large & Mid Cap Fund",
  "6": "Sectoral/ Thematic",
  "7": "ELSS",
  "8": "Aggressive Hybrid Fund",
  "9": "Long Duration Fund",
  "10": "Mid Cap Fund",
  "11": "Flexi Cap Fund",
  "12": "Index Funds",
  "13": "Value Fund",
  "14": "Dynamic Bond",
  "15": "Low Duration Fund",
  "16": "Corporate Bond Fund",
  "17": "Retirement Fund",
  "18": "Gilt",
  "19": "Conservative Hybrid Fund",
  "20": "Medium Duration Fund",
  "21": "Dynamic Asset Allocation or Balanced Advantage",
  "22": "Children's Fund",
  "23": "Money Market Fund",
  "24": "Overnight Fund",
  "25": "Income",
  "26": "Floater Fund",
  "27": "Multi Cap Fund",
  "28": "Short Duration Fund",
  "29": "Ultra Short Duration Fund",
  "30": "Growth",
  "31": "Liquid",
  "32": "Credit Risk Fund",
  "33": "Multi Asset Allocation",
  "34": "Equity Savings",
  "35": "Other ETFs",
  "36": "FoF Domestic",
  "37": "Floating Rate",
  "38": "Focused Fund",
  "39": "Balanced Hybrid Fund",
  "40": "Small Cap Fund",
  "41": "Dividend Yield Fund",
  "42": "Arbitrage Fund",
  "43": "Gold ETF",
  "44": "Gilt Fund with 10 year constant duration",
  "45": "Banking and PSU Fund",
  "46": "FoF Overseas",
  "47": "Balanced",
  "48": "Money Market",
  "49": "Contra Fund"
};


module.exports = {listOfAMC,listOfCategory,subCategory}